<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Obat;
use Carbon\Carbon;

class ObatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $obatData = [
            // ANALGESIK & ANTIPIRETIK
            [
                'kode_obat' => 'PCT500',
                'nama_obat' => 'Paracetamol 500mg',
                'nama_generik' => 'Paracetamol',
                'pabrik' => 'Kimia Farma',
                'kategori' => 'Analgesik',
                'satuan' => 'tablet',
                'harga' => 500,
                'stok_tersedia' => 1000,
                'stok_minimum' => 100,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Obat pereda nyeri dan penurun demam',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'IBU400',
                'nama_obat' => 'Ibuprofen 400mg',
                'nama_generik' => 'Ibuprofen',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Analgesik',
                'satuan' => 'tablet',
                'harga' => 2000,
                'stok_tersedia' => 500,
                'stok_minimum' => 50,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Anti inflamasi non steroid (NSAID)',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'ASP100',
                'nama_obat' => 'Aspirin 100mg',
                'nama_generik' => 'Asam Asetilsalisilat',
                'pabrik' => 'Bayer',
                'kategori' => 'Analgesik',
                'satuan' => 'tablet',
                'harga' => 1500,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Antiplatelet dan analgesik',
                'is_aktif' => true,
            ],

            // ANTIBIOTIK
            [
                'kode_obat' => 'AMX500',
                'nama_obat' => 'Amoxicillin 500mg',
                'nama_generik' => 'Amoxicillin',
                'pabrik' => 'Sanbe Farma',
                'kategori' => 'Antibiotik',
                'satuan' => 'kapsul',
                'harga' => 3000,
                'stok_tersedia' => 800,
                'stok_minimum' => 80,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antibiotik spektrum luas golongan penisilin',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'CIP500',
                'nama_obat' => 'Ciprofloxacin 500mg',
                'nama_generik' => 'Ciprofloxacin',
                'pabrik' => 'Kalbe Farma',
                'kategori' => 'Antibiotik',
                'satuan' => 'tablet',
                'harga' => 8000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addMonths(18),
                'deskripsi' => 'Antibiotik golongan fluoroquinolone',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'AZI500',
                'nama_obat' => 'Azithromycin 500mg',
                'nama_generik' => 'Azithromycin',
                'pabrik' => 'Pfizer',
                'kategori' => 'Antibiotik',
                'satuan' => 'tablet',
                'harga' => 12000,
                'stok_tersedia' => 150,
                'stok_minimum' => 15,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antibiotik makrolide spektrum luas',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'CEF500',
                'nama_obat' => 'Cefixime 200mg',
                'nama_generik' => 'Cefixime',
                'pabrik' => 'Novartis',
                'kategori' => 'Antibiotik',
                'satuan' => 'kapsul',
                'harga' => 15000,
                'stok_tersedia' => 100,
                'stok_minimum' => 10,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antibiotik sefalosporin generasi ketiga',
                'is_aktif' => true,
            ],

            // ANTASIDA & MAAG
            [
                'kode_obat' => 'OME20',
                'nama_obat' => 'Omeprazole 20mg',
                'nama_generik' => 'Omeprazole',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Lambung',
                'satuan' => 'kapsul',
                'harga' => 5000,
                'stok_tersedia' => 400,
                'stok_minimum' => 40,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Proton pump inhibitor untuk maag',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'RAN150',
                'nama_obat' => 'Ranitidine 150mg',
                'nama_generik' => 'Ranitidine',
                'pabrik' => 'Kalbe Farma',
                'kategori' => 'Lambung',
                'satuan' => 'tablet',
                'harga' => 3500,
                'stok_tersedia' => 350,
                'stok_minimum' => 35,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'H2 receptor antagonist untuk maag',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'ANT500',
                'nama_obat' => 'Antasida DOEN',
                'nama_generik' => 'Aluminum Hydroxide + Magnesium Hydroxide',
                'pabrik' => 'Kimia Farma',
                'kategori' => 'Lambung',
                'satuan' => 'tablet',
                'harga' => 1000,
                'stok_tersedia' => 600,
                'stok_minimum' => 60,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Penetral asam lambung',
                'is_aktif' => true,
            ],

            // ANTIDIARE & PENCERNAAN
            [
                'kode_obat' => 'LOP2',
                'nama_obat' => 'Loperamide 2mg',
                'nama_generik' => 'Loperamide HCl',
                'pabrik' => 'Sanbe Farma',
                'kategori' => 'Pencernaan',
                'satuan' => 'kapsul',
                'harga' => 2500,
                'stok_tersedia' => 250,
                'stok_minimum' => 25,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antidiare untuk mengurangi frekuensi BAB',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'ORS200',
                'nama_obat' => 'Oralit',
                'nama_generik' => 'Oral Rehydration Salt',
                'pabrik' => 'Pharos',
                'kategori' => 'Pencernaan',
                'satuan' => 'sachet',
                'harga' => 3000,
                'stok_tersedia' => 500,
                'stok_minimum' => 50,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Larutan rehidrasi oral untuk diare',
                'is_aktif' => true,
            ],

            // ANTIHISTAMIN & ALERGI
            [
                'kode_obat' => 'CTM4',
                'nama_obat' => 'CTM 4mg',
                'nama_generik' => 'Chlorpheniramine Maleate',
                'pabrik' => 'Kimia Farma',
                'kategori' => 'Antihistamin',
                'satuan' => 'tablet',
                'harga' => 800,
                'stok_tersedia' => 800,
                'stok_minimum' => 80,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Antihistamin untuk alergi dan gatal',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'LOR10',
                'nama_obat' => 'Loratadine 10mg',
                'nama_generik' => 'Loratadine',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Antihistamin',
                'satuan' => 'tablet',
                'harga' => 3500,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antihistamin generasi kedua tanpa efek sedasi',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'CET10',
                'nama_obat' => 'Cetirizine 10mg',
                'nama_generik' => 'Cetirizine HCl',
                'pabrik' => 'Kalbe Farma',
                'kategori' => 'Antihistamin',
                'satuan' => 'tablet',
                'harga' => 4000,
                'stok_tersedia' => 400,
                'stok_minimum' => 40,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antihistamin untuk rinitis alergi dan urtikaria',
                'is_aktif' => true,
            ],

            // BATUK & PILEK
            [
                'kode_obat' => 'DEX15',
                'nama_obat' => 'Dextromethorphan HBr 15mg',
                'nama_generik' => 'Dextromethorphan',
                'pabrik' => 'Sanbe Farma',
                'kategori' => 'Batuk',
                'satuan' => 'tablet',
                'harga' => 2000,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antitusif untuk batuk kering',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'GUA100',
                'nama_obat' => 'Guaifenesin 100mg',
                'nama_generik' => 'Guaifenesin',
                'pabrik' => 'Pharos',
                'kategori' => 'Batuk',
                'satuan' => 'tablet',
                'harga' => 1500,
                'stok_tersedia' => 400,
                'stok_minimum' => 40,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Ekspektoran untuk batuk berdahak',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'PSE60',
                'nama_obat' => 'Pseudoephedrine 60mg',
                'nama_generik' => 'Pseudoephedrine HCl',
                'pabrik' => 'Novartis',
                'kategori' => 'Pilek',
                'satuan' => 'tablet',
                'harga' => 3000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Dekongestan untuk hidung tersumbat',
                'is_aktif' => true,
            ],

            // VITAMIN & SUPLEMEN
            [
                'kode_obat' => 'VBC500',
                'nama_obat' => 'Vitamin C 500mg',
                'nama_generik' => 'Ascorbic Acid',
                'pabrik' => 'Kalbe Farma',
                'kategori' => 'Vitamin',
                'satuan' => 'tablet',
                'harga' => 2500,
                'stok_tersedia' => 600,
                'stok_minimum' => 60,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Vitamin C untuk daya tahan tubuh',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'VBD1000',
                'nama_obat' => 'Vitamin D3 1000 IU',
                'nama_generik' => 'Cholecalciferol',
                'pabrik' => 'Blackmores',
                'kategori' => 'Vitamin',
                'satuan' => 'softgel',
                'harga' => 8000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Vitamin D untuk kesehatan tulang',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'VBB50',
                'nama_obat' => 'Vitamin B Complex',
                'nama_generik' => 'B Complex',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Vitamin',
                'satuan' => 'tablet',
                'harga' => 3500,
                'stok_tersedia' => 400,
                'stok_minimum' => 40,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Vitamin B kompleks untuk metabolisme',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'ZINC20',
                'nama_obat' => 'Zinc 20mg',
                'nama_generik' => 'Zinc Sulfate',
                'pabrik' => 'Kimia Farma',
                'kategori' => 'Mineral',
                'satuan' => 'tablet',
                'harga' => 2000,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Suplemen zinc untuk daya tahan tubuh',
                'is_aktif' => true,
            ],

            // ANTIHIPERTENSI
            [
                'kode_obat' => 'CAP25',
                'nama_obat' => 'Captopril 25mg',
                'nama_generik' => 'Captopril',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'tablet',
                'harga' => 1500,
                'stok_tersedia' => 500,
                'stok_minimum' => 50,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'ACE inhibitor untuk hipertensi',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'AML5',
                'nama_obat' => 'Amlodipine 5mg',
                'nama_generik' => 'Amlodipine',
                'pabrik' => 'Pfizer',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'tablet',
                'harga' => 3000,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Calcium channel blocker untuk hipertensi',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'HCTZ25',
                'nama_obat' => 'Hydrochlorothiazide 25mg',
                'nama_generik' => 'Hydrochlorothiazide',
                'pabrik' => 'Sanbe Farma',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'tablet',
                'harga' => 2000,
                'stok_tersedia' => 400,
                'stok_minimum' => 40,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Diuretik untuk hipertensi',
                'is_aktif' => true,
            ],

            // DIABETES
            [
                'kode_obat' => 'MET500',
                'nama_obat' => 'Metformin 500mg',
                'nama_generik' => 'Metformin HCl',
                'pabrik' => 'Kalbe Farma',
                'kategori' => 'Antidiabetik',
                'satuan' => 'tablet',
                'harga' => 2500,
                'stok_tersedia' => 600,
                'stok_minimum' => 60,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antidiabetik golongan biguanide',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'GLI5',
                'nama_obat' => 'Glimepiride 2mg',
                'nama_generik' => 'Glimepiride',
                'pabrik' => 'Novartis',
                'kategori' => 'Antidiabetik',
                'satuan' => 'tablet',
                'harga' => 5000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Sulfonilurea untuk diabetes tipe 2',
                'is_aktif' => true,
            ],

            // OBAT TOPIKAL
            [
                'kode_obat' => 'BETA15',
                'nama_obat' => 'Betamethasone Cream 0.1%',
                'nama_generik' => 'Betamethasone',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Topikal',
                'satuan' => 'tube',
                'harga' => 15000,
                'stok_tersedia' => 100,
                'stok_minimum' => 10,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Kortikosteroid topikal untuk peradangan kulit',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'GENT10',
                'nama_obat' => 'Gentamicin Cream 0.1%',
                'nama_generik' => 'Gentamicin Sulfate',
                'pabrik' => 'Sanbe Farma',
                'kategori' => 'Topikal',
                'satuan' => 'tube',
                'harga' => 12000,
                'stok_tersedia' => 80,
                'stok_minimum' => 8,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Antibiotik topikal untuk infeksi kulit',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'POV10',
                'nama_obat' => 'Povidone Iodine 10%',
                'nama_generik' => 'Povidone Iodine',
                'pabrik' => 'Pharos',
                'kategori' => 'Antiseptik',
                'satuan' => 'botol',
                'harga' => 25000,
                'stok_tersedia' => 50,
                'stok_minimum' => 5,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Antiseptik untuk luka dan pembedahan',
                'is_aktif' => true,
            ],

            // OBAT MATA
            [
                'kode_obat' => 'CHLORA',
                'nama_obat' => 'Chloramphenicol Eye Drop',
                'nama_generik' => 'Chloramphenicol',
                'pabrik' => 'Kimia Farma',
                'kategori' => 'Mata',
                'satuan' => 'botol',
                'harga' => 8000,
                'stok_tersedia' => 100,
                'stok_minimum' => 10,
                'tanggal_kadaluarsa' => Carbon::now()->addMonths(18),
                'deskripsi' => 'Tetes mata antibiotik untuk infeksi mata',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'GENTA',
                'nama_obat' => 'Gentamicin Eye Drop',
                'nama_generik' => 'Gentamicin Sulfate',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Mata',
                'satuan' => 'botol',
                'harga' => 12000,
                'stok_tersedia' => 80,
                'stok_minimum' => 8,
                'tanggal_kadaluarsa' => Carbon::now()->addMonths(18),
                'deskripsi' => 'Tetes mata antibiotik spektrum luas',
                'is_aktif' => true,
            ],

            // OBAT KONTRASEPSI
            [
                'kode_obat' => 'PIL21',
                'nama_obat' => 'Pil KB Kombinasi',
                'nama_generik' => 'Ethinylestradiol + Levonorgestrel',
                'pabrik' => 'Bayer',
                'kategori' => 'Kontrasepsi',
                'satuan' => 'strip',
                'harga' => 15000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Kontrasepsi oral kombinasi',
                'is_aktif' => true,
            ],

            // OBAT GINJAL & SALURAN KEMIH
            [
                'kode_obat' => 'FUR40',
                'nama_obat' => 'Furosemide 40mg',
                'nama_generik' => 'Furosemide',
                'pabrik' => 'Sanbe Farma',
                'kategori' => 'Diuretik',
                'satuan' => 'tablet',
                'harga' => 3000,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Diuretik kuat untuk edema dan hipertensi',
                'is_aktif' => true,
            ],

            // OBAT ASMA & SESAK
            [
                'kode_obat' => 'SAL2',
                'nama_obat' => 'Salbutamol 2mg',
                'nama_generik' => 'Salbutamol',
                'pabrik' => 'Glaxo',
                'kategori' => 'Bronkodilator',
                'satuan' => 'tablet',
                'harga' => 4000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Bronkodilator untuk asma dan PPOK',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'THEO200',
                'nama_obat' => 'Theophylline 200mg',
                'nama_generik' => 'Theophylline',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Bronkodilator',
                'satuan' => 'tablet',
                'harga' => 3500,
                'stok_tersedia' => 250,
                'stok_minimum' => 25,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Bronkodilator untuk asma kronik',
                'is_aktif' => true,
            ],

            // OBAT NYERI SENDI
            [
                'kode_obat' => 'DIC50',
                'nama_obat' => 'Diclofenac 50mg',
                'nama_generik' => 'Diclofenac Sodium',
                'pabrik' => 'Novartis',
                'kategori' => 'Analgesik',
                'satuan' => 'tablet',
                'harga' => 4000,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'NSAID untuk nyeri sendi dan otot',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'MEL15',
                'nama_obat' => 'Meloxicam 15mg',
                'nama_generik' => 'Meloxicam',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Analgesik',
                'satuan' => 'tablet',
                'harga' => 6000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'NSAID selektif COX-2 untuk artritis',
                'is_aktif' => true,
            ],

            // OBAT ANTISEPTIK & LUKA
            [
                'kode_obat' => 'ALK70',
                'nama_obat' => 'Alcohol 70%',
                'nama_generik' => 'Ethyl Alcohol',
                'pabrik' => 'Kimia Farma',
                'kategori' => 'Antiseptik',
                'satuan' => 'botol',
                'harga' => 10000,
                'stok_tersedia' => 100,
                'stok_minimum' => 10,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(5),
                'deskripsi' => 'Antiseptik untuk membersihkan luka',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'H2O2',
                'nama_obat' => 'Hydrogen Peroxide 3%',
                'nama_generik' => 'Hydrogen Peroxide',
                'pabrik' => 'Pharos',
                'kategori' => 'Antiseptik',
                'satuan' => 'botol',
                'harga' => 8000,
                'stok_tersedia' => 80,
                'stok_minimum' => 8,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Pembersih luka dan antiseptik',
                'is_aktif' => true,
            ],

            // OBAT JANTUNG
            [
                'kode_obat' => 'ISOM5',
                'nama_obat' => 'Isosorbide Dinitrate 5mg',
                'nama_generik' => 'Isosorbide Dinitrate',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'tablet',
                'harga' => 2500,
                'stok_tersedia' => 300,
                'stok_minimum' => 30,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Vasodilator untuk angina pektoris',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'DIG025',
                'nama_obat' => 'Digoxin 0.25mg',
                'nama_generik' => 'Digoxin',
                'pabrik' => 'Kimia Farma',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'tablet',
                'harga' => 3000,
                'stok_tersedia' => 200,
                'stok_minimum' => 20,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(3),
                'deskripsi' => 'Glikosida jantung untuk gagal jantung',
                'is_aktif' => true,
            ],

            // OBAT HORMONAL
            [
                'kode_obat' => 'PRED5',
                'nama_obat' => 'Prednisolone 5mg',
                'nama_generik' => 'Prednisolone',
                'pabrik' => 'Dexa Medica',
                'kategori' => 'Kortikosteroid',
                'satuan' => 'tablet',
                'harga' => 4000,
                'stok_tersedia' => 250,
                'stok_minimum' => 25,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Kortikosteroid untuk inflamasi dan alergi',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'DEXA4',
                'nama_obat' => 'Dexamethasone 4mg',
                'nama_generik' => 'Dexamethasone',
                'pabrik' => 'Sanbe Farma',
                'kategori' => 'Kortikosteroid',
                'satuan' => 'tablet',
                'harga' => 5000,
                'stok_tersedia' => 150,
                'stok_minimum' => 15,
                'tanggal_kadaluarsa' => Carbon::now()->addYears(2),
                'deskripsi' => 'Kortikosteroid poten untuk inflamasi berat',
                'is_aktif' => true,
            ],
        ];

        foreach ($obatData as $obat) {
            Obat::create($obat);
        }
    }
}
